# ============================================================================
# THE n_iterations CONVENTION
# ============================================================================
# Across every sampler in this repository, `n_iterations` is the TOTAL number
# of iterations the chain runs, and the leading `burn_in` of them are
# discarded. Asking for 20,000 iterations with a burn-in of 5,000 runs 20,000
# steps and returns 15,000 draws.
#
# The two families used to disagree: metropolis_hastings.R ran `burn_in` steps
# on top of `n_iterations`, so the same pair of arguments produced a 25,000
# step chain there and a 20,000 step chain here. Both readings are defensible
# in isolation, but not in a benchmark. Wall-clock runtime and ESS/second are
# reported per algorithm, and under the old split two algorithms handed
# identical arguments did different amounts of work - which is the one thing a
# timing comparison cannot tolerate. Total chain length also makes the cost of
# a run readable from the argument alone.

# ============================================================================
# WHEN ADAPTATION HAPPENS
# ============================================================================
# Both adaptive samplers take `adapt_start` and `adapt_stop`, and both default
# to adapting from iteration 100 until the end of burn-in.
#
# An earlier version did the opposite: it held the proposal fixed at
# diag(0.1^2) for the whole of burn-in and only began adapting afterwards.
# That wastes the burn-in - the phase whose entire purpose is to find the
# proposal - and then estimates the covariance from exactly the badly-mixed
# stretch that resulted. It also leaves every retained draw generated by a
# still-changing transition kernel.
#
# The last point is what settles the default. ESS and R-hat are defined for a
# fixed kernel. Freezing adaptation at the end of burn-in means the retained
# draws come from one kernel, so those diagnostics measure what their names
# say. Pass `adapt_stop = n_iterations` for the textbook Adaptive Metropolis
# of Haario et al. (2001), which keeps adapting forever and stays ergodic by
# diminishing adaptation; the diagnostics are then approximations.

# ============================================================================
# ADAPTIVE METROPOLIS (AM)
# ============================================================================
adaptive_metropolis <- function(target_log_density, initial_value,
                                n_iterations, burn_in = 1000,
                                initial_cov = NULL, adapt_interval = 50,
                                adapt_start = 100, adapt_stop = burn_in) {
  d <- length(initial_value)

  # n_iterations is the whole chain, burn_in comes out of it. The guard is
  # repeated verbatim in each algorithm file rather than factored out, so that
  # any one of them can still be sourced on its own.
  if (n_iterations < 2 || burn_in < 0 || burn_in >= n_iterations) {
    stop("need n_iterations >= 2 and 0 <= burn_in < n_iterations; got ",
         "n_iterations = ", n_iterations, ", burn_in = ", burn_in)
  }

  # Initialize covariance
  if (is.null(initial_cov)) {
    initial_cov <- diag(0.1^2, d)
  }

  chain <- matrix(nrow = n_iterations, ncol = d)
  accepted <- logical(n_iterations)
  current <- initial_value
  current_logp <- target_log_density(current)
  chain[1, ] <- current

  # Covariance of the chain so far, maintained by Welford's recursion rather
  # than recomputed with cov(chain[1:(t-1), ]) at every adaptation.
  #
  # The two agree to floating-point precision - there is a test pinning that -
  # but the recompute costs O(t*d^2) each time it fires, so the price of the
  # adaptation grows with the chain and a longer run pays superlinearly. At
  # 26 parameters, going from 10,000 to 50,000 iterations took AM from 1.6 s
  # to 20.6 s, a 13x cost for 5x the work. The recursion is O(d^2) per
  # iteration regardless of length, which is what makes a chain long enough to
  # actually converge affordable.
  n_seen <- 1
  run_mean <- current
  run_scatter <- matrix(0, d, d)   # sum of (x - mean)(x - mean)'
  sample_cov <- initial_cov
  n_adapted <- 0

  for (t in 2:n_iterations) {
    # Refresh the proposal covariance from everything seen so far.
    if (t >= adapt_start && t <= adapt_stop && t %% adapt_interval == 0 &&
        n_seen >= 2) {
      # Small diagonal keeps the covariance positive definite for mvrnorm.
      sample_cov <- run_scatter / (n_seen - 1) + diag(1e-6, d)
      n_adapted <- n_adapted + 1
    }

    # Propose using current covariance
    proposal <- MASS::mvrnorm(1, current, 2.38^2 / d * sample_cov)
    proposal_logp <- target_log_density(proposal)

    # Accept/reject
    log_alpha <- proposal_logp - current_logp
    if (log(runif(1)) < log_alpha) {
      current <- proposal
      current_logp <- proposal_logp
      accepted[t] <- TRUE
    }

    chain[t, ] <- current

    # Absorb the new state, so that at the top of iteration t + 1 the running
    # statistics cover exactly chain[1:t, ].
    n_seen <- n_seen + 1
    delta <- current - run_mean
    run_mean <- run_mean + delta / n_seen
    run_scatter <- run_scatter + tcrossprod(delta, current - run_mean)
  }

  # Iteration 1 is the initial value and had no proposal, so it never counts
  # towards the acceptance rate.
  list(
    samples = chain[(burn_in + 1):n_iterations, , drop = FALSE],
    acceptance_rate = mean(accepted[max(burn_in + 1, 2):n_iterations]),
    full_chain = chain,
    n_adaptations = n_adapted,
    final_cov = sample_cov
  )
}

# ============================================================================
# ROBUST ADAPTIVE METROPOLIS (RAM)
# ============================================================================
robust_adaptive_metropolis <- function(target_log_density, initial_value,
                                       n_iterations, burn_in = 1000,
                                       target_acceptance = 0.234,
                                       adapt_start = 100, adapt_stop = burn_in,
                                       shape_interval = 50,
                                       shape_window = NULL) {
  d <- length(initial_value)

  # n_iterations is the whole chain, burn_in comes out of it. The guard is
  # repeated verbatim in each algorithm file rather than factored out, so that
  # any one of them can still be sourced on its own.
  if (n_iterations < 2 || burn_in < 0 || burn_in >= n_iterations) {
    stop("need n_iterations >= 2 and 0 <= burn_in < n_iterations; got ",
         "n_iterations = ", n_iterations, ", burn_in = ", burn_in)
  }

  # The shape is estimated from a trailing window of the chain. A fixed 500
  # was hardcoded here, so lengthening the run bought the scale adaptation
  # more iterations but left the shape estimate reading the same short tail.
  # It now grows with the chain, with 500 as the floor for short runs.
  if (is.null(shape_window)) {
    shape_window <- max(500, floor(n_iterations / 20))
  }

  chain <- matrix(nrow = n_iterations, ncol = d)
  accepted <- logical(n_iterations)
  current <- initial_value
  current_logp <- target_log_density(current)
  chain[1, ] <- current

  # RAM-specific: scale and shape adaptation
  scale <- 1.0
  shape <- diag(d)

  for (t in 2:n_iterations) {
    if (t >= adapt_start && t <= adapt_stop) {
      # Robbins-Monro step size, decaying as 1/k^0.6 from the first adapting
      # iteration. Keyed to adapt_start rather than to burn_in so that moving
      # the adaptation window does not also change the decay schedule.
      gamma_t <- 1 / (t - adapt_start + 1)^0.6

      # Update scale based on acceptance rate
      accept_t <- as.numeric(accepted[t - 1])
      scale <- scale * exp(gamma_t * (accept_t - target_acceptance))

      # Update shape (simplified version: Vihola's rank-one Cholesky update
      # replaced by a windowed empirical covariance)
      if (t %% shape_interval == 0) {
        recent_samples <- chain[max(1, t - shape_window):(t - 1), , drop = FALSE]
        if (nrow(recent_samples) >= 2) {
          shape <- cov(recent_samples) + diag(1e-6, d)
        }
      }
    }

    # Propose
    proposal_cov <- scale^2 * shape
    proposal <- MASS::mvrnorm(1, current, proposal_cov)
    proposal_logp <- target_log_density(proposal)

    # Accept/reject
    log_alpha <- proposal_logp - current_logp
    if (log(runif(1)) < log_alpha) {
      current <- proposal
      current_logp <- proposal_logp
      accepted[t] <- TRUE
    }

    chain[t, ] <- current
  }

  # Iteration 1 is the initial value and had no proposal, so it never counts
  # towards the acceptance rate.
  list(
    samples = chain[(burn_in + 1):n_iterations, , drop = FALSE],
    acceptance_rate = mean(accepted[max(burn_in + 1, 2):n_iterations]),
    full_chain = chain,
    final_scale = scale,
    shape_window = shape_window
  )
}

# ============================================================================
# NON-ADAPTIVE RANDOM WALK METROPOLIS (BASELINE)
# ============================================================================
# The control condition: a proposal fixed before the run and never touched
# again, so that any difference against AM and RAM is attributable to the
# adaptation and nothing else.
#
# `proposal_scale` is the per-coordinate standard deviation of the target,
# and the proposal is proposal_sd / sqrt(d) times it. Supplying it is what
# makes this a fair control rather than a straw man. The scale used to be the
# absolute constant (2.38 / sqrt(d)) * 0.1, with the 0.1 carrying only the
# comment "Add 0.1 multiplier"; across the benchmark's posteriors the
# per-parameter standard deviations span seven orders of magnitude, from
# 0.0012 to 9668, so one absolute step size meant near-total rejection on the
# tightest model and near-total acceptance on the widest. The 0.00005 to
# 0.998 acceptance range that produced was a property of that constant, not
# of random walk Metropolis.
#
# Handing the baseline the marginal scales does give it information AM and
# RAM have to learn. That is the intended question: with the scales already
# known, is there anything left for adaptation to do? The answer is the
# correlation structure, which a diagonal proposal cannot represent -
# earnings-earn_height has a posterior condition number of 1.4 million.
random_walk_baseline <- function(target_log_density, initial_value,
                                 n_iterations, burn_in = 1000,
                                 proposal_sd = 2.38, proposal_scale = NULL) {
  d <- length(initial_value)

  # n_iterations is the whole chain, burn_in comes out of it. The guard is
  # repeated verbatim in each algorithm file rather than factored out, so that
  # any one of them can still be sourced on its own.
  if (n_iterations < 2 || burn_in < 0 || burn_in >= n_iterations) {
    stop("need n_iterations >= 2 and 0 <= burn_in < n_iterations; got ",
         "n_iterations = ", n_iterations, ", burn_in = ", burn_in)
  }

  # Default to a unit-scale target, which is the Roberts et al. (1997) setting
  # for proposal_sd = 2.38.
  if (is.null(proposal_scale)) {
    proposal_scale <- rep(1, d)
  }
  if (length(proposal_scale) != d) {
    stop("proposal_scale must have one entry per parameter (", d, "); got ",
         length(proposal_scale))
  }

  # Optimal scaling for a random walk in d dimensions (Roberts et al., 1997).
  scaled_sd <- (proposal_sd / sqrt(d)) * proposal_scale

  chain <- matrix(nrow = n_iterations, ncol = d)
  accepted <- logical(n_iterations)
  current <- initial_value
  current_logp <- target_log_density(current)
  chain[1, ] <- current

  for (t in 2:n_iterations) {
    proposal <- current + rnorm(d, 0, scaled_sd)
    proposal_logp <- target_log_density(proposal)

    log_alpha <- proposal_logp - current_logp
    if (log(runif(1)) < log_alpha) {
      current <- proposal
      current_logp <- proposal_logp
      accepted[t] <- TRUE
    }

    chain[t, ] <- current
  }

  # Iteration 1 is the initial value and had no proposal, so it never counts
  # towards the acceptance rate.
  list(
    samples = chain[(burn_in + 1):n_iterations, , drop = FALSE],
    acceptance_rate = mean(accepted[max(burn_in + 1, 2):n_iterations]),
    full_chain = chain,
    proposal_sd = scaled_sd
  )
}
